#!/bin/ksh -p
#
# This file and its contents are supplied under the terms of the
# Common Development and Distribution License ("CDDL"), version 1.0.
# You may only use this file in accordance with the terms of version
# 1.0 of the CDDL.
#
# A full copy of the text of the CDDL should have accompanied this
# source. A copy of the CDDL is also available via the Internet at
# http://www.illumos.org/license/CDDL.

# OmniOSce needs this to exist, but in Tribblix it does nothing
# (it could run setup_fw, but it's not obvious that an LX zone
# managing its own ipf rules makes sense in Tribblix)

exit 0
